spring:
  application:
    name: straightmail
  mail:
    host: localhost
    username: foo
    password: bar
    port: 1025
    default-sender: "user@example.com"
    default-template: "default"
  freemarker:
    template-loader-path:
      - classpath:templates
